INSERT INTO SAMPLE_POST (POST_NO, USER_ID, TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES (1, 'test1', 'hello1', 'sample content1', now(), now());
INSERT INTO SAMPLE_POST (POST_NO, USER_ID, TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES (2, 'test2', 'hello2', 'sample content2', now(), now());
INSERT INTO SAMPLE_POST (POST_NO, USER_ID, TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES (3, 'test3', 'hello3', 'sample content3', now(), now());
INSERT INTO SAMPLE_POST (POST_NO, USER_ID, TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES (4, 'test4', 'hello4', 'sample content4', now(), now());
INSERT INTO SAMPLE_POST (POST_NO, USER_ID, TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES (5, 'test5', 'hello5', 'sample content5', now(), now());

INSERT INTO SAMPLE_COMMENT (COMMENT_NO, POST_NO, CONTENT, CREATED_AT, UPDATED_AT) VALUES (1, 1, 'comment content1', now(), now()); 
INSERT INTO SAMPLE_COMMENT (COMMENT_NO, POST_NO, CONTENT, CREATED_AT, UPDATED_AT) VALUES (2, 2, 'comment content2', now(), now());
INSERT INTO SAMPLE_COMMENT (COMMENT_NO, POST_NO, CONTENT, CREATED_AT, UPDATED_AT) VALUES (3, 3, 'comment content3', now(), now());
INSERT INTO SAMPLE_COMMENT (COMMENT_NO, POST_NO, CONTENT, CREATED_AT, UPDATED_AT) VALUES (4, 4, 'comment content4', now(), now());
INSERT INTO SAMPLE_COMMENT (COMMENT_NO, POST_NO, CONTENT, CREATED_AT, UPDATED_AT) VALUES (5, 5, 'comment content5', now(), now());